Bathroom: '#a2fc88'
Bathroom-sink: '#7990d9'
Bedroom: '#8f9cf7'
Chair: '#7cb61d'
Closet: '#5643dd'
Clothes-folded: '#7ef2fc'
Computer: '#833fdb'
Countertop-wood: '#7dda3a'
Kitchen: '#b1bdb5'
Laundry-basket: '#775f17'
Office: '#b4d0d4'
Oven: '#66bcb2'
Pepper: '#7c3514'
Salt: '#943328'
Shelf: '#796ff2'
Single-bed: '#6f0d6b'
Toilet: '#6806be'
