Bathroom: '#58b33e'
Bathroom-sink: '#7990d9'
Bedroom: '#530a98'
Chair: '#7cb61d'
Closet: '#5643dd'
Clothes-folded: '#7ef2fc'
Computer: '#833fdb'
Countertop-wood: '#7dda3a'
Kitchen: '#775f17'
Laundry-basket: '#8b2078'
Office: '#76937f'
Oven: '#66bcb2'
Pepper: '#7c3514'
Salt: '#943328'
Shelf: '#796ff2'
Single-bed: '#6f0d6b'
Toilet: '#6806be'
